CREATE TABLE IF NOT EXISTS url (
    id int(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
    url tinytext NOT NULL,
    code varchar(10) NOT NULL,
    create_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
